---
title: "Honey Bees - DESeq"
author: Lindsay Rutter
output:
  packagedocs::package_docs:
    toc: true
    toc_collapse: true
vignette: >
  %\VignetteEngine{packagedocs::redirect}
---

<meta http-equiv="content-type" content="text/html;charset=utf-8" />

```{r global_options, include=FALSE}
# R output pre blocks are styled by default to indicate output
knitr::opts_chunk$set(
  comment = NA,
  cache = TRUE,
  fig.height = 8,
  fig.width = 10
)
```

```{r}
library(DESeq2)
library(RColorBrewer)
library(data.table)
library(ggplot2)
library(gplots)
library(GGally)

thisPath <- getwd()

data <- readRDS("../data/data.Rds")
data <- as.matrix(data)

coldata = data.frame(row.names = colnames(data), treatment = unlist(lapply(colnames(data), function (x) unlist(strsplit(x, "[.]"))[1])))

dds = DESeqDataSetFromMatrix(countData = data, colData = coldata, design = ~ treatment)
dds <- DESeq(dds)
```

We can examine pairwise combinations of all samples

```{r}
uTreat <- unique(unlist(lapply(colnames(data), function (x) unlist(strsplit(x, "[.]"))[1])))
allPairs = data.frame(Treatment1 = factor(), Treatment2 = factor(), NumberDEG = numeric())
dataMetrics <- list()

for (i in 1:(length(uTreat)-1)){
  for (j in (i+1):length(uTreat)){
    res <- results(dds, contrast=c("treatment",uTreat[i],uTreat[j]))
    hist(res$pvalue, breaks=20, col="grey", main=paste("pvalue for", uTreat[i], "and", uTreat[j]))
    degLength <- length(which((res@listData)$padj <0.05))

    metrics = as.data.frame(res@listData)
    metrics = cbind(ID = res@rownames, metrics)
    metrics$ID = as.character(metrics$ID)
    dataMetrics[[paste0(uTreat[i], "_", uTreat[j])]] <- metrics
    
    t1Length <- length(which(metrics[which(metrics$padj <0.05),]$log2FoldChange>0))
    t2Length <- length(which(metrics[which(metrics$padj <0.05),]$log2FoldChange<0))
    
    RDC <- metrics[which(metrics[which(metrics$padj <0.05),]$log2FoldChange>0),]$ID
    RDR <- metrics[which(metrics[which(metrics$padj <0.05),]$log2FoldChange<0),]$ID
    RD_DIET <- metrics[which(metrics$padj <0.05),]$ID
    saveRDS(RDC, file="RDC.Rds")
    saveRDS(RDR, file="RDR.Rds")
    saveRDS(RD_DIET, file="RD_DIET.Rds")
    
    allPairs = rbind(allPairs, data.frame(Treatment1 = uTreat[i], Treatment2 = uTreat[j], NumberDEG = degLength, Treatment1Larger = t1Length, Treatment2Larger = t2Length))
  }
}
allPairs <- allPairs[order(allPairs$NumberDEG),]
allPairs
saveRDS(data, file="data.Rds")
saveRDS(dataMetrics, file="dataMetrics.Rds")
```

```{r}
plotDispEsts(dds, ylim = c(1e-6, 1e1))
```

Taking rlog transformation for EDA.

```{r}
rld <- rlog(dds)
rldDF <- as.data.frame(assay(rld))
saveRDS(rldDF, file="dataRLD.Rds")
```

```{r}
sampleDists <- dist(t(assay(rld)))
sampleDistMatrix <- as.matrix(sampleDists)
rownames(sampleDistMatrix) <- paste(rld$treatment, rld$patient, sep="-")
colnames(sampleDistMatrix) <- NULL
colours = colorRampPalette(rev(brewer.pal(9, "Blues")))(255)
heatmap.2(sampleDistMatrix, trace="none", col=colours)
```

```{r}
print(plotPCA(rld, intgroup="treatment") + geom_label(aes(label = name), label.size=0.001))
```

```{r}
ggparcoord(data.frame(log(as.data.frame(assay(rld))/colMeans(as.data.frame(assay(rld))))), columns=1:6, alphaLines=0, boxplot=TRUE, scale="globalminmax") + coord_flip()
```

```{r}
dds <- estimateSizeFactors(dds)
normDat <- counts(dds, normalized=TRUE)
normDat <- as.data.frame(normDat)
ggparcoord(data.frame(log(normDat)/colMeans(normDat)), columns=1:6, alphaLines=0, boxplot=TRUE, scale="globalminmax") + coord_flip()
```